Leveling
karst-club/karst pull request #65
Opened 2020-11-24 04:04 UTC by sarah-johnson

2020-11-24 04:08 UTC, vonkow approved these changes

2020-11-24 04:10 UTC, sarah-johnson commented
DON'T MERGE THIS!
There's nothing stopping me from shipping a bogus Knack Name

TO DO:
 - [ ] Unknown Knack Names should fail (criteria: knack named "foo" should cause a failing merge request)
 - [ ] Support levels/specifics on knacks (i.e. implement "starts with" rule)

2020-11-24 04:11 UTC, vonkow requested changes
See comment above

2020-11-27 00:08 UTC, sarah-johnson commented
I opened !68 for the other things just to keep it separate.

2020-11-27 00:09 UTC, merged